version: "3.8"

services:
  nameservice:
    build: ./NameService
    ports:
      - "8081:80"
    networks:
      - app-network

  rentalservice:
    build: ./RentalService
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_JSON={"nameservice.url":"http://nameservice:80"}
    depends_on:
      - nameservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
